-- CREATE DATABASE QUANLYSHUSHI
CREATE DATABASE QUANLYSHUSHI
GO

-- USE QUANLYSHUSHI
USE QUANLYSHUSHI
GO

-- CREATE TABLE LOGINSYSTEM
CREATE TABLE LOGINSYSTEM
(
	ID VARCHAR(100) NOT NULL,
	PASS VARCHAR(1000) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CONSTRAINT PK_LOGINSYSTEM_ID
	PRIMARY KEY (ID)
)
GO

-- CREATE TABLE KHACHHANGVIP
CREATE TABLE KHACHHANGVIP
(
	ID VARCHAR(5) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100),
	CONSTRAINT PK_KHACHHANGVIP_ID
	PRIMARY KEY (ID)
)
GO

-- CREATE TABLE CHUCVU
CREATE TABLE CHUCVU
(
	ID VARCHAR(5) NOT NULL,
	NAME NVARCHAR(100) NOT NULL
	CONSTRAINT PK_CHUCVU_ID
	PRIMARY KEY(ID)
)
GO

-- CREATE TABLE NHANVIEN
CREATE TABLE NHANVIEN
(
	ID VARCHAR(5) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	PHONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SEX BIT,
	BRITHDAY VARCHAR(100),
	LUONG FLOAT NOT NULL,
	IDCHUCVU VARCHAR(5) NOT NULL,
	CONSTRAINT PK_NHANVIEN_ID 
	PRIMARY KEY (ID),
	CONSTRAINT FK_NHANVIEN_IDCHUCVU
	FOREIGN KEY(IDCHUCVU)
	REFERENCES dbo.CHUCVU(ID)
)
GO

-- CREATE TABLE LUONGTAM
CREATE TABLE LUONGTAM
(	
	IDNHANVIEN VARCHAR(5) NOT NULL,
	LUONG FLOAT NOT NULL
	CONSTRAINT PK_LUONGTAM_IDNHANVIEN
	PRIMARY KEY(IDNHANVIEN),
	CONSTRAINT FK_LUONGTAM_IDNHANVIEN
	FOREIGN KEY (IDNHANVIEN)
	REFERENCES dbo.NHANVIEN(ID)
)
GO

-- CREATE TABLE CANGHI
CREATE TABLE CANGHI
(	
	NGAYNGHICA VARCHAR(50) NOT NULL,
	GIOLAM VARCHAR(50) NOT NULL,
	IDNHANVIEN VARCHAR(5) NOT NULL,
	CONSTRAINT PK_CANGHI_IDNHANVIEN
	FOREIGN KEY (IDNHANVIEN)
	REFERENCES dbo.NHANVIEN(ID)
)
GO

-- CREATE TABLE DANHSACHCA
CREATE TABLE DANHSACHCA
(
	ID VARCHAR(5) NOT NULL,
	THU NVARCHAR(50) NOT NULL,
	GIOLAM VARCHAR(20) NOT NULL,
	GIOKETTHUC VARCHAR(20) NOT NULL,
	CHECKCA BIT,
	IDNHANVIEN VARCHAR(5) NOT NULL,
	CONSTRAINT PK_DANHSACHCA_ID
	PRIMARY KEY(ID),
	CONSTRAINT FK_DANHSACHCA_IDNHANVIEN
	FOREIGN KEY(IDNHANVIEN)
	REFERENCES dbo.NHANVIEN(ID)
)
GO

-- CREATE TABLE NGAYNGHI
CREATE TABLE NGAYNGHI
(
	NGAYNGHI VARCHAR(50) NOT NULL,
	IDNHANVIEN VARCHAR(5)
	CONSTRAINT FK_SONGAYNGHI_IDNHANVIEN
	FOREIGN KEY (IDNHANVIEN)
	REFERENCES dbo.NHANVIEN(ID)
)
GO

-- CREATE TABLE BAN
CREATE TABLE BAN
(
	ID CHAR(3) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	TRANGTHAI NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_BAN_ID
	PRIMARY KEY (ID)
)
GO

-- CREATE TABLE FOOD
CREATE TABLE FOOD
(
	ID VARCHAR(5) NOT NULL,
	NAME NVARCHAR(200) NOT NULL,
	PRICE FLOAT NOT NULL,
	CONSTRAINT PK_FOOD_ID
	PRIMARY KEY (ID)
)
GO

-- CREATE TABLE BILL
CREATE TABLE BILL
(
	ID VARCHAR(5) NOT NULL,
	THOIGIANLAP VARCHAR(50) NOT NULL,
	THOIGIANXUAT NVARCHAR(50) NOT NULL DEFAULT N'Chưa Thanh Toán',
	TONGTIEN FLOAT NOT NULL,
	IDBAN CHAR(3) NOT NULL,
	CONSTRAINT PK_BILL_ID
	PRIMARY KEY (ID),
	CONSTRAINT FK_BILL_IDBAN
	FOREIGN KEY (IDBAN)
	REFERENCES dbo.BAN(ID)
)
GO

-- CREATE TABLE BILLFOOD
CREATE TABLE BILLFOOD
(
	IDBILL VARCHAR(5) NOT NULL,
	IDFOOD VARCHAR(5) NOT NULL,
	NAME NVARCHAR(200) NOT NULL,
	PRICE FLOAT NOT NULL,
	SOLUONG SMALLINT NOT NULL,
	THANHTIEN FLOAT NOT NULL,
	IDBAN CHAR(3) NOT NULL,
	CONSTRAINT FK_BILLFOOD_IDBILL
	FOREIGN KEY (IDBILL)
	REFERENCES dbo.BILL(ID),
)
GO

-- INSERT TABLE LOGINSYSTEM
INSERT INTO dbo.LOGINSYSTEM
        ( ID, PASS, EMAIL )
VALUES  ( 'admin', -- ID - varchar(100)
          '2121!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!@@@@@@@@@@@@@@@&&&&&&&&&&&&&&^^^^^^^^^^^^^^#########%%%================<<<<<<<<???????44A4A4AX174808080X11281F1F1FX131C3C3C3X1195', -- PASS - varchar(1000)
          'cuncon271295@gmai.com'  -- EMAIL - varchar(100)
          )
GO

-- INSERT TABLE FOOD
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0001', -- ID - varchar(5)
          N'Shu shi tròn', -- NAME - nvarchar(200)
          60000.00  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0002', -- ID - varchar(5)
          N'Shu shi khối', -- NAME - nvarchar(200)
          70000.00 -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0003', -- ID - varchar(5)
          N'Shu shi vuông', -- NAME - nvarchar(200)
          80000.00  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0004', -- ID - varchar(5)
          N'Shu shi đa giác', -- NAME - nvarchar(200)
          '100000.00'  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0005', -- ID - varchar(5)
          N'Shu shi kẹp', -- NAME - nvarchar(200)
          '120000.00'  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0006', -- ID - varchar(5)
          N'Shu shi hay', -- NAME - nvarchar(200)
          60000.00  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0007', -- ID - varchar(5)
          N'Shu shi nè', -- NAME - nvarchar(200)
          60000.00  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0008', -- ID - varchar(5)
          N'Shu shi đó', -- NAME - nvarchar(200)
          60000.00  -- PRICE - varchar(100)
          )
GO
INSERT INTO dbo.FOOD
        ( ID, NAME, PRICE )
VALUES  ( 'F0009', -- ID - varchar(5)
          N'Shu shi ơi', -- NAME - nvarchar(200)
          75000.00 -- PRICE - varchar(100)
          )
GO

-- INSERT TABLE TABLE
DECLARE @i INT = 1
DECLARE @Ma VARCHAR (100)

WHILE(@i < 21)
BEGIN
	SET @Ma = 'B' + REPLICATE('0', 2 - LEN(CAST(@i AS VARCHAR))) + CAST(@i AS NVARCHAR)
	INSERT INTO dbo.BAN
	        ( ID, NAME, TRANGTHAI )
	VALUES  ( @Ma, -- ID - char(3)
	          N'Bàn ' + CAST(@i AS NVARCHAR), -- NAME - nvarchar(100)
	          N'Trống')
	SET @i += 1
END
GO

-- CREATE FUNCTION
CREATE FUNCTION FCMANHANVIEN()
RETURNS VARCHAR(5)
AS
BEGIN	
	IF((SELECT COUNT(*) FROM dbo.NHANVIEN) = 0)
	BEGIN
		RETURN 'N0001'
	END
	ELSE
		DECLARE @MA VARCHAR(5) = 'N0001'
		DECLARE @I INT = 1
		WHILE EXISTS ( SELECT ID FROM dbo.NHANVIEN WHERE ID = @MA)
		BEGIN
			SET @I += 1
			SET @MA = 'N' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
		END
	RETURN @MA
END
GO

CREATE FUNCTION FCTHEMNHANVIEN()
RETURNS VARCHAR(5)
BEGIN
	IF((SELECT COUNT(*) FROM dbo.NHANVIEN) = 0)
	BEGIN
		RETURN 'N0001'
	END
	ELSE
		DECLARE @MA VARCHAR(5) = 'N0001'
		DECLARE @I INT = 1
		WHILE EXISTS ( SELECT ID FROM dbo.NHANVIEN WHERE ID = @MA)
		BEGIN
			SET @I += 1
			SET @MA = 'N' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
		END
	RETURN @MA
END
GO

CREATE FUNCTION FCTHEMMONAN()
RETURNS VARCHAR(5)
BEGIN
	IF ((SELECT COUNT(*) FROM dbo.FOOD) = 0)
	BEGIN
		RETURN 'F0001'
	END
	ELSE
		DECLARE @MA VARCHAR(5) = 'F0001'
		DECLARE @I INT = 1
		WHILE EXISTS (SELECT ID FROM dbo.FOOD WHERE ID = @MA)
		BEGIN
			SET @I += 1
			SET @MA = 'F' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
		END
	RETURN @MA
END
GO

CREATE FUNCTION FCMABILL()
RETURNS VARCHAR(5)
AS
BEGIN
	IF ((SELECT COUNT(*) FROM dbo.BILL) = 0)
	BEGIN
		RETURN 'B0001'
	END
	ELSE
		DECLARE @MA VARCHAR(5) = 'B0001'
		DECLARE @I INT = 1
		WHILE EXISTS(SELECT ID FROM dbo.BILL WHERE ID = @MA)
		BEGIN
			SET @I += 1
			SET @MA = 'B' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
		END
	RETURN @MA
END
GO

CREATE PROCEDURE SP_THEMBILLFOOD
@IDFOOD VARCHAR(5), @NAME NVARCHAR(200), @PRICE FLOAT, @SOLUONG SMALLINT, @THANHTIEN FLOAT, @IDBAN CHAR(3)
AS
BEGIN
	DECLARE @MA VARCHAR(5) = 'B0001'
	DECLARE @I INT = 1
	WHILE EXISTS (SELECT ID FROM dbo.BILL WHERE ID = @MA )
	BEGIN
		SET @I += 1
		SET @MA = 'B' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
	END
	SET @MA = 'B' + REPLICATE('0', 4 - LEN(CAST(@I - 1 AS VARCHAR))) + CAST(@I -1 AS VARCHAR) 
	INSERT INTO dbo.BILLFOOD
	        ( IDBILL ,
	          IDFOOD ,
	          NAME ,
			  PRICE,
	          SOLUONG ,
	          THANHTIEN ,
	          IDBAN
	        )
	VALUES  (  @MA, -- IDBILL - varchar(5)
	          @IDFOOD , -- IDFOOD - varchar(5)
	          @NAME , -- NAME - nvarchar(200)
	          @PRICE,
			  @SOLUONG , -- SOLUONG - smallint
	          @THANHTIEN , -- THANHTIEN - float
	          @IDBAN  -- IDBAN - char(3)
	        )
END
GO

CREATE FUNCTION FCTHEMCHUCVU()
RETURNS VARCHAR(5)
BEGIN
	IF ((SELECT COUNT(*) FROM dbo.CHUCVU ) = 0)
	BEGIN
		RETURN 'C0001'
	END
	ELSE
		DECLARE @I INT = 1
		DECLARE @MA VARCHAR(5) = 'C0001'
		BEGIN
			WHILE EXISTS (SELECT ID FROM dbo.CHUCVU WHERE ID = @MA)
			BEGIN
				SET @I += 1
				SET @MA = 'C' + REPLICATE(0, 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
			END
		END
	RETURN @MA
END
GO

CREATE FUNCTION FCTHEMCA()
RETURNS VARCHAR(5)
BEGIN
	IF((SELECT COUNT(*) FROM dbo.DANHSACHCA) = 0)
	BEGIN
		RETURN 'C0001'
	END
	ELSE
	BEGIN
		DECLARE @MA VARCHAR(5) = 'C0001'
		DECLARE @I INT = 1
		WHILE EXISTS (SELECT ID FROM dbo.DANHSACHCA WHERE ID = @MA)
		BEGIN
			SET @I += 1
			SET @MA = 'C' + REPLICATE('0', 4 - LEN(CAST(@I AS VARCHAR))) + CAST(@I AS VARCHAR)
		END
	END
	RETURN @MA
END
GO

CREATE FUNCTION FCTHEMLUONGTAM()
RETURNS VARCHAR(5)
BEGIN
	DECLARE @MA VARCHAR(5) = 'N0001'
	DECLARE @I INT = 1
	IF ( ( SELECT COUNT(*) FROM dbo.NHANVIEN ) = 0)
	BEGIN
		RETURN 'N0001'
	END
	WHILE EXISTS ( SELECT ID FROM dbo.NHANVIEN WHERE ID = @MA)
	BEGIN
		SET @I += 1
		SET @MA = 'N' + REPLICATE('0', 4 - LEN(CAST( @I AS VARCHAR))) + CAST(@I AS VARCHAR)
	END
	RETURN 'N' + REPLICATE('0', 4 - LEN(CAST(@I - 1 AS VARCHAR))) + CAST(@I - 1 AS VARCHAR)
END
GO

-- INSERT TALBE CHUCVU
INSERT INTO dbo.CHUCVU
        ( ID, NAME )
VALUES  ( dbo.FCTHEMCHUCVU(), -- ID - varchar(5)
          N'Tạp Vụ'  -- NAME - nvarchar(100)
          )
GO

-- INSERT TABLE NHANVIEN
INSERT INTO dbo.NHANVIEN
        ( ID ,
          NAME ,
          PHONE ,
          EMAIL ,
          SEX ,
          BRITHDAY ,
          LUONG,
		  IDCHUCVU
        )
VALUES  ( 'N0001' , -- ID - varchar(5)
          N'Nhân viên 1' , -- NAME - nvarchar(100)
          '123456789' , -- PHONE - varchar(15)
          'nhanvien1@gmail.com' , -- EMAIL - varchar(100)
          1 , -- SEX - bit
           '12-27-1995', -- BRITHDAY - date
          3000000.00,  -- LUONG - varchar(100)
		  'C0001' -- IDCHUCVU - int
        )
GO
INSERT INTO dbo.NHANVIEN
        ( ID ,
          NAME ,
          PHONE ,
          EMAIL ,
          SEX ,
          BRITHDAY ,
          LUONG,
		  IDCHUCVU
        )
VALUES  ( 'N0002' , -- ID - varchar(5)
          N'Nhân viên 2' , -- NAME - nvarchar(100)
          '123456789' , -- PHONE - varchar(15)
          'nhanvien2@gmail.com' , -- EMAIL - varchar(100)
          1 , -- SEX - bit
           '12-27-1995', -- BRITHDAY - date
          5000000.00, -- LUONG - varchar(100)
		  'C0001' -- IDCHUCVU - int
        )
GO
INSERT INTO dbo.NHANVIEN
        ( ID ,
          NAME ,
          PHONE ,
          EMAIL ,
          SEX ,
          BRITHDAY ,
          LUONG,
		  IDCHUCVU
        )
VALUES  ( 'N0003' , -- ID - varchar(5)
          N'Nhân viên 3' , -- NAME - nvarchar(100)
          '123456789' , -- PHONE - varchar(15)
          'nhanvien3@gmail.com' , -- EMAIL - varchar(100)
          1 , -- SEX - bit
           '', -- BRITHDAY - date
          8000000.00,  -- LUONG - varchar(100)
		  'C0001' -- IDCHUCVU - int
        )
GO

--SELECT BF.IDBILL, BF.IDFOOD, BF.NAME, BF.SOLUONG, BF.THANHTIEN
--FROM dbo.FOOD AS F INNER JOIN dbo.BILLFOOD AS BF
--ON BF.IDFOOD = F.ID INNER JOIN dbo.BILL AS B 
--ON BF.IDBILL = B.ID WHERE B.IDBAN = 'B02'
--GO

--UPDATE BAN SET TRANGTHAI = 'Có người' WHERE ID = 'B03'

--UPDATE dbo.BILLFOOD SET SOLUONG = 2, THANHTIEN = 150000.00 WHERE IDBILL = 'B0004' AND IDFOOD = 'F0009' AND IDBAN = 'B15'

--UPDATE dbo.BILL SET TONGTIEN = 470000.00 WHERE ID = 'B0003'

--SELECT BF.NAME, SUM(BF.SOLUONG) AS SOLUONG, SUM(BF.THANHTIEN) FROM dbo.BILLFOOD AS BF
--WHERE BF.IDFOOD = BF.IDFOOD
--GROUP BY BF.NAME
--GO

--SELECT BF.NAME, COUNT(BF.SOLUONG), SUM(BF.THANHTIEN) FROM dbo.BILLFOOD AS BF, 
--dbo.BILL AS B WHERE BF.IDBILL = B.ID AND SUBSTRING(B.THOIGIANLAP, 0, 6) = '10-06'
--GROUP BY BF.NAME

--SELECT BF.IDBILL, BF.IDFOOD, BF.NAME, BF.PRICE, BF.SOLUONG, BF.THANHTIEN, BF.IDBAN FROM BILLFOOD AS BF INNER JOIN BILL AS B ON BF.IDBILL = B.ID
--GO
